"""added expenses table

Revision ID: 48144ffb3a1b
Revises: 1144506bf9c4
Create Date: 2025-07-14 09:58:46.579118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48144ffb3a1b'
down_revision = '1144506bf9c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenses',
    sa.Column('expense_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('expense_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('expenses')
    # ### end Alembic commands ###
